### PR TITLE
Select User Improvements

### PR DESCRIPTION
**Pull request by mandoz**
1. Added missing "name" parameters to `users_db`.
2. Moved users filtering for the selecting specific users to the initial compilation of effective users, instead of being part of the user management task.
3. General clean up of the python code for the usersdb compilation.

### CODE REVIEW

**Comment by ahelal** [comment]
@mandoz  not sure how to react to that :) ?

**Comment by mandoz** [comment]
@ahelal i was waiting to talk to you before I continue working on this PR

**Comment by mandoz** [comment]
@ahelal Fixed, I updated the PR and the PR description. :)

**Comment by mandoz** [comment]
Ping :)

**Comment by ahelal** [comment]
It seems okay, But can you not use PEP8 multi line. ?
mean while I will write a couple of tests to add then merge

**Comment by mandoz** [comment]
Why no multi-line?

**Comment by ahelal** [comment]
mixing styles in same code is harder to follow.

**Comment by mandoz** [comment]
Well its the right way to do it :) But ok i'll do it for you.

**Comment by ahelal** [comment]
Although we dont have a guidelines, but we kind of follow that https://github.com/ansible/ansible/blob/devel/CODING_GUIDELINES.md

**Comment by mandoz** [comment]
@ahelal Done.

**Comment by mandoz** [comment]
@ahelal can you create a release so we can update dependencies?

**Pull request merged**
